#!/bin/bash
#
# GHOST Gather - Consolidated Report Generator
# Aggregates findings from all hunters into unified Markdown report
#
# Usage:
#   ghost-gather.sh markdown     - Full Markdown report
#   ghost-gather.sh executive    - Executive summary only
#   ghost-gather.sh technical    - Technical findings only
#   ghost-gather.sh json         - JSON export
#

set -e

GHOST_ROOT="/tmp/ghost"
ENGAGEMENT="${GHOST_ENGAGEMENT:-$GHOST_ROOT/active}"
[ -L "$ENGAGEMENT" ] && ENGAGEMENT=$(readlink -f "$ENGAGEMENT")

STATE_FILE="$ENGAGEMENT/state.json"
FINDINGS_FILE="$ENGAGEMENT/findings.json"
RUNLOG="$ENGAGEMENT/runlog.jsonl"
HUNTERS_DIR="$ENGAGEMENT/hunters"

# Colors (for terminal output, stripped from file output)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Get engagement metadata
get_metadata() {
    local engagement_id=$(jq -r '.engagement_id' "$STATE_FILE")
    local target=$(jq -r '.target' "$STATE_FILE")
    local created=$(jq -r '.created_at' "$STATE_FILE")
    local phase=$(jq -r '.phase' "$STATE_FILE")

    echo "engagement_id=$engagement_id"
    echo "target=$target"
    echo "created=$created"
    echo "phase=$phase"
}

# Count findings by severity
count_findings() {
    local critical=$(jq '[.findings[] | select(.severity == "critical")] | length' "$FINDINGS_FILE")
    local high=$(jq '[.findings[] | select(.severity == "high")] | length' "$FINDINGS_FILE")
    local medium=$(jq '[.findings[] | select(.severity == "medium")] | length' "$FINDINGS_FILE")
    local low=$(jq '[.findings[] | select(.severity == "low")] | length' "$FINDINGS_FILE")
    local info=$(jq '[.findings[] | select(.severity == "info")] | length' "$FINDINGS_FILE")

    echo "critical=$critical"
    echo "high=$high"
    echo "medium=$medium"
    echo "low=$low"
    echo "info=$info"
}

# Generate executive summary
generate_executive() {
    eval $(get_metadata)
    eval $(count_findings)

    cat << EOF
# Penetration Test Executive Summary

## Engagement Overview

| Field | Value |
|-------|-------|
| Engagement ID | $engagement_id |
| Target | $target |
| Assessment Date | $created |
| Current Status | $phase |

## Risk Summary

| Severity | Count |
|----------|-------|
| Critical | $critical |
| High | $high |
| Medium | $medium |
| Low | $low |
| Informational | $info |

## Overall Risk Assessment

EOF

    # Calculate risk level
    if [ "$critical" -gt 0 ]; then
        echo "**Risk Level: CRITICAL**"
        echo ""
        echo "The assessment identified **$critical critical** and **$high high** severity vulnerabilities that pose immediate risk to the organization. Immediate remediation is strongly recommended."
    elif [ "$high" -gt 0 ]; then
        echo "**Risk Level: HIGH**"
        echo ""
        echo "The assessment identified **$high high** severity vulnerabilities that should be addressed promptly to reduce organizational risk."
    elif [ "$medium" -gt 0 ]; then
        echo "**Risk Level: MEDIUM**"
        echo ""
        echo "The assessment identified **$medium medium** severity vulnerabilities. While not immediately critical, these should be scheduled for remediation."
    else
        echo "**Risk Level: LOW**"
        echo ""
        echo "No critical or high severity vulnerabilities were identified. Continue monitoring and address lower severity findings as part of regular maintenance."
    fi

    echo ""
    echo "## Key Findings"
    echo ""

    # List critical and high findings
    jq -r '.findings[] | select(.severity == "critical" or .severity == "high") | "- **[\(.severity | ascii_upcase)]** \(.title): \(.description)"' "$FINDINGS_FILE" 2>/dev/null || echo "No critical or high findings."

    echo ""
    echo "## Strategic Recommendations"
    echo ""
    echo "1. Address all critical findings immediately"
    echo "2. Schedule remediation for high severity findings within 30 days"
    echo "3. Review and remediate medium severity findings within 90 days"
    echo "4. Implement continuous security monitoring"
    echo ""
    echo "---"
    echo "*Report generated by GHOST on $(date -Iseconds)*"
}

# Generate technical findings
generate_technical() {
    eval $(get_metadata)

    cat << EOF
# Technical Findings Report

## Engagement Details

- **Engagement ID**: $engagement_id
- **Target**: $target
- **Assessment Date**: $created
- **Report Generated**: $(date -Iseconds)

---

EOF

    # Critical findings
    echo "## Critical Findings"
    echo ""
    local critical_count=$(jq '[.findings[] | select(.severity == "critical")] | length' "$FINDINGS_FILE")
    if [ "$critical_count" -gt 0 ]; then
        jq -r '.findings[] | select(.severity == "critical") | "### \(.title)\n\n**ID**: \(.id)\n**Discovered By**: \(.agent)\n**Discovered At**: \(.discovered_at)\n\n**Description**:\n\(.description)\n\n---\n"' "$FINDINGS_FILE"
    else
        echo "No critical findings."
        echo ""
    fi

    # High findings
    echo "## High Severity Findings"
    echo ""
    local high_count=$(jq '[.findings[] | select(.severity == "high")] | length' "$FINDINGS_FILE")
    if [ "$high_count" -gt 0 ]; then
        jq -r '.findings[] | select(.severity == "high") | "### \(.title)\n\n**ID**: \(.id)\n**Discovered By**: \(.agent)\n**Discovered At**: \(.discovered_at)\n\n**Description**:\n\(.description)\n\n---\n"' "$FINDINGS_FILE"
    else
        echo "No high severity findings."
        echo ""
    fi

    # Medium findings
    echo "## Medium Severity Findings"
    echo ""
    local medium_count=$(jq '[.findings[] | select(.severity == "medium")] | length' "$FINDINGS_FILE")
    if [ "$medium_count" -gt 0 ]; then
        jq -r '.findings[] | select(.severity == "medium") | "### \(.title)\n\n**ID**: \(.id)\n**Discovered By**: \(.agent)\n**Discovered At**: \(.discovered_at)\n\n**Description**:\n\(.description)\n\n---\n"' "$FINDINGS_FILE"
    else
        echo "No medium severity findings."
        echo ""
    fi

    # Low and Info findings (condensed)
    echo "## Low and Informational Findings"
    echo ""
    jq -r '.findings[] | select(.severity == "low" or .severity == "info") | "- **[\(.severity | ascii_upcase)]** \(.title)"' "$FINDINGS_FILE" 2>/dev/null || echo "None."
    echo ""

    # Discovered assets
    echo "## Discovered Assets"
    echo ""
    echo "### Ports and Services"
    echo ""
    jq -r '.assets[] | select(.type == "port") | "- \(.value) - \(.info)"' "$FINDINGS_FILE" 2>/dev/null || echo "None discovered."
    echo ""

    echo "### URLs and Endpoints"
    echo ""
    jq -r '.assets[] | select(.type == "url") | "- \(.value)"' "$FINDINGS_FILE" 2>/dev/null || echo "None discovered."
    echo ""

    echo "### Other Assets"
    echo ""
    jq -r '.assets[] | select(.type != "port" and .type != "url") | "- [\(.type)] \(.value)"' "$FINDINGS_FILE" 2>/dev/null || echo "None."
    echo ""

    # Credentials (sanitized)
    echo "## Credentials Discovered"
    echo ""
    local cred_count=$(jq '.credentials | length' "$FINDINGS_FILE")
    if [ "$cred_count" -gt 0 ]; then
        echo "| Username | Type | Source |"
        echo "|----------|------|--------|"
        jq -r '.credentials[] | "| \(.username) | \(.type) | \(.source) |"' "$FINDINGS_FILE"
        echo ""
        echo "*Note: Credential values redacted from report. See engagement files for full details.*"
    else
        echo "No credentials discovered."
    fi
    echo ""

    echo "---"
    echo "*Report generated by GHOST on $(date -Iseconds)*"
}

# Generate full markdown report
generate_markdown() {
    generate_executive
    echo ""
    echo "---"
    echo ""
    generate_technical
}

# Export as JSON
export_json() {
    jq -s '.[0] * .[1] | {
        metadata: {
            engagement_id: .engagement_id,
            target: .target,
            created_at: .created_at,
            phase: .phase
        },
        summary: {
            critical: ([.findings[] | select(.severity == "critical")] | length),
            high: ([.findings[] | select(.severity == "high")] | length),
            medium: ([.findings[] | select(.severity == "medium")] | length),
            low: ([.findings[] | select(.severity == "low")] | length),
            info: ([.findings[] | select(.severity == "info")] | length)
        },
        findings: .findings,
        assets: .assets,
        credentials: (.credentials | map(del(.secret)))
    }' "$STATE_FILE" "$FINDINGS_FILE"
}

# Collect evidence from hunters
collect_evidence() {
    local output_dir="${1:-$ENGAGEMENT/reports/evidence}"
    mkdir -p "$output_dir"

    echo "Collecting evidence from hunters..."
    for hunter_dir in "$HUNTERS_DIR"/*/; do
        local hunter=$(basename "$hunter_dir")
        if [ -d "$hunter_dir/evidence" ]; then
            echo "  - Collecting from $hunter"
            mkdir -p "$output_dir/$hunter"
            cp -r "$hunter_dir/evidence/"* "$output_dir/$hunter/" 2>/dev/null || true
        fi
    done
    echo "Evidence collected to: $output_dir"
}

# Main
case "${1:-help}" in
    markdown|md)
        generate_markdown
        ;;
    executive|exec)
        generate_executive
        ;;
    technical|tech)
        generate_technical
        ;;
    json)
        export_json
        ;;
    evidence)
        collect_evidence "$2"
        ;;
    *)
        echo "GHOST Gather - Consolidated Report Generator"
        echo ""
        echo "Usage: $0 <command>"
        echo ""
        echo "Commands:"
        echo "  markdown    - Full Markdown report (executive + technical)"
        echo "  executive   - Executive summary only"
        echo "  technical   - Technical findings only"
        echo "  json        - JSON export"
        echo "  evidence    - Collect evidence from all hunters"
        echo ""
        echo "Examples:"
        echo "  $0 markdown > report.md"
        echo "  $0 executive > exec-summary.md"
        echo "  $0 json > findings.json"
        ;;
esac
